version : "3"
services: 
  node-app:
    build:
      context: . # path of dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=name
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=name
      - MONGO_INITDB_ROOT_PASSWORD=mypassword     # - MONGO_USER=name